name: Build .NET App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]

    env:
      Solution_Name: ColorsToNumbers.sln  # <== Tên file .sln thật của bạn

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # hoặc 7.0.x nếu bạn dùng phiên bản cũ hơn

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the project
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload .exe as artifact
      uses: actions/upload-artifact@v4
      with:
        name: BuildExe
        path: |
          **\bin\${{ matrix.configuration }}\*.exe
